-- ======================================
-- insert.sql
-- 
-- Author: NKhoa
--
-- Description:
-- ..
--
-- Revision history:
-- ..
-- ======================================

-- Insert values into Patient