CREATE or REPLACE PROCEDURE UpdatePCR(
    startDate IN ADMISSION_DATE%TYPE
)
BEGIN
    
    UPDATE PCRTEST
    SET PCRTEST_CT_VALUE = NULL, RESULT = "POSITIVE"
    WHERE PCRTEST_TESTID IN ( 
        SELECT Test_ID 
        FROM TESTING, ADMISSION
        WHERE TESTING_STAFFID = ADMISSION_STAFFID AND TESTING_ADMITTED_PATIENTID = ADMISSION_PATIENTID AND TO_DATE(ADMISSION_DATE, 'MM/DD/YYYY') >= TO_DATE('01/09/2020', 'MM/DD/YYYY'))
END UpdatePCR;