DELIMITER $$ 

CREATE PROCEDURE UpdatePCR(
    startDate DATE
)
BEGIN
    UPDATE PCRTEST
    SET PCRTEST_CT_VALUE = NULL, PCRTEST_RESULT = 'POSITIVE'
    WHERE PCRTEST_TESTID IN ( 
        SELECT Testing_TestID 
        FROM TESTING
        JOIN ADMISSION ON TESTING.TESTING_STAFFID = ADMISSION.ADMISSION_STAFFID 
            AND TESTING.TESTING_PATIENTID = ADMISSION.ADMISSION_PATIENTID 
        WHERE ADMISSION.ADMISSION_DATE >= '2020-01-09');
END$$

DELIMITER ;